# Site settings
title: "Thomas Lomas' Résumé / Curriculum Vitae / Ramblings"
markdown: kramdown
description: "This is my personal Résumé / Curriculum Vitae with some ramblings too"
url: "http://thomaslomas.com"
repository: ThomasLomas/thomaslomas.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

plugins:
  - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
