# Site settings
title: "Thomas Lomas' Résumé / Curriculum Vitae / Ramblings"
markdown: kramdown
description: "This is my personal Résumé / Curriculum Vitae with some ramblings too"
url: "http://thomaslomas.com"

gems:
    - jekyll-feed

kramdown:
    input: GFM
    syntax_highlighter: rouge

exclude:
    [vendor]
